/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package design;

import dao.SinhVienDAO;
import design.popup.SinhvienJFrame;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.SinhVien;

/**
 *
 * @author nguye
 */
public class SinhvienJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HocvienJPanel
     */
    private SinhvienJPanel sinhvienJPanel = this;
    public SinhvienJPanel() {
        initComponents();
        
        tbSinhVien.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // Lấy số hàng đã được nhấp
                if (e.getClickCount() == 2) {
                    int row = tbSinhVien.getSelectedRow();
                    SinhVien sinhvien = new SinhVien();
                    sinhvien.setId((int) tbSinhVien.getValueAt(row, 0));
                    sinhvien.setTen((String) tbSinhVien.getValueAt(row, 1));
                    sinhvien.setNgay_sinh((Date) tbSinhVien.getValueAt(row, 2));
                    sinhvien.setGioi_tinh((String) tbSinhVien.getValueAt(row, 3));
                    sinhvien.setSđt((String) tbSinhVien.getValueAt(row, 4));
                    sinhvien.setEmail((String) tbSinhVien.getValueAt(row, 5));
                    sinhvien.setDia_chi((String) tbSinhVien.getValueAt(row, 6));
                    sinhvien.setGpa((BigDecimal) tbSinhVien.getValueAt(row, 7));
                    sinhvien.setId_lopbienche((int)tbSinhVien.getValueAt(row, 8));
                    SinhvienJFrame frame = new SinhvienJFrame(sinhvienJPanel, sinhvien, true);
                    frame.setTitle("Sửa thông tin");
                
                    frame.setVisible(true);
                }
                
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }

            
        });
        
        JTableHeader thead = tbSinhVien.getTableHeader();
        
        thead.setFont(new Font("Segoe", Font.ITALIC,16));
        thead.setBackground(new Color(200,255,255));
        loaddata();
    }

    public void loaddata() {
        
        try {
            DefaultTableModel model = (DefaultTableModel) tbSinhVien.getModel();
            model.setRowCount(0);
            ArrayList<SinhVien> list = SinhVienDAO.list();
            for (SinhVien item : list) {
                model.addRow(new Object[]{item.getId(), item.getTen(), item.getNgay_sinh(),
                    item.getGioi_tinh(), item.getSđt(), item.getEmail(), item.getDia_chi(),
                    item.getGpa(), item.getId_lopbienche()});
            }
        } catch (Exception e ) {
            
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSinhVien = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 680));

        jPanel1.setBackground(new java.awt.Color(230, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 680));

        jButton1.setBackground(new java.awt.Color(122, 122, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbSinhVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SV", "Họ Tên", "Ngày Sinh", "Giới Tính", "SDT", "Email", "Địa Chỉ", "GPA", "Mã Lớp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSinhVien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbSinhVien.setGridColor(new java.awt.Color(0, 0, 153));
        tbSinhVien.setPreferredSize(new java.awt.Dimension(980, 600));
        tbSinhVien.setRequestFocusEnabled(false);
        tbSinhVien.setRowHeight(30);
        tbSinhVien.setRowMargin(10);
        tbSinhVien.setSelectionBackground(new java.awt.Color(255, 153, 153));
        tbSinhVien.setSelectionForeground(new java.awt.Color(255, 0, 51));
        tbSinhVien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbSinhVien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbSinhVien.setShowGrid(true);
        tbSinhVien.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(tbSinhVien);

        jButton2.setBackground(new java.awt.Color(112, 112, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tên sinh viên");

        jButton5.setBackground(new java.awt.Color(112, 112, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Tìm Kiếm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SinhVien sinhvien = new SinhVien();
        SinhvienJFrame frame = new SinhvienJFrame(sinhvienJPanel,sinhvien, false);
        frame.setTitle("Thêm Sinh Viên");
        frame.setVisible(true);
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tbSinhVien.getSelectedRow();

        if (selectedRowIndex != -1) {
            // Lấy giá trị của cột CID từ dòng được chọn
            int id = (int) tbSinhVien.getValueAt(selectedRowIndex, 0);

            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn xoa?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                int a = SinhVienDAO.delete(id);
                if(a>0) {
                    loaddata();
                }
            }
        } else {
            System.out.println("Vui lòng chọn một dòng để xóa!");
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            if(jTextField1.getText().isEmpty()) {
                loaddata() ;
                return;
            }
            DefaultTableModel model = (DefaultTableModel) tbSinhVien.getModel();
            model.setRowCount(0);
            ArrayList<SinhVien> list = SinhVienDAO.find(jTextField1.getText());
            for (SinhVien item : list) {
                model.addRow(new Object[]{item.getId(), item.getTen(), item.getNgay_sinh(),
                    item.getGioi_tinh(), item.getSđt(), item.getEmail(), item.getDia_chi(),
                    item.getGpa(), item.getId_lopbienche()});
            }
        } catch (Exception e ) {

        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbSinhVien;
    // End of variables declaration//GEN-END:variables
}
